### ISSUE TITLE
data-src属性无效

### ISSUE THREAD

**Issue by xiaoz1987** [lixianbin1/imgZoom#4]
打开的图片还是src的路径，不是data-src的属性

**Comment by lixianbin1** [comment]
我原本的设想是打开图片是src, data-src 是用来解决图片加载慢的问题,先使用压缩过的占位小图,等data-src 上的图片加载完后,替换掉占位小图.,然后之前的版本没弄.在介绍里也没提这个属性 现在我重新构建了一版. 支持 data-src 属性了.
[](https://github.com/lixianbin1/imgZoom/releases/tag/v0.9.0)

**Comment by lixianbin1** [comment]
https://github.com/lixianbin1/imgZoom/releases/tag/v0.9.0
